# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0023_auto_20161203_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eresume',
            name='cvlink',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='elaborate',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='emailid',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='fbid',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='fblink',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='field',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='i',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='j',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='location',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='state',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='twitterlink',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='work1',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='work2',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='work3',
        ),
        migrations.RemoveField(
            model_name='eresume',
            name='work4',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='LinkedIn',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='city',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='educational_qualifications_1',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='educational_qualifications_2',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='educational_qualifications_3',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='educational_qualifications_4',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='emailid',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='experience_1',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='experience_2',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='experience_3',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='experience_4',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='fbid',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='greetings',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='hobbies_1',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='hobbies_2',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='hobbies_3',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='hobbies_4',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='objective_achievements',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='objective_line1',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='skills_1',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='skills_2',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='skills_3',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='skills_4',
        ),
        migrations.RemoveField(
            model_name='resume_input',
            name='state',
        ),
    ]
